#include "interface.h"
#include "keyboard.h"
#include "neural_network.h"
#include "ptask.h"
#include "sensor.h"

int main() {
    int index;

    Task task_table[] = {{-1, simulate_sensor_task, 25, 300},
                         {-1, graphic_task, 30, 20},
                         {-1, neural_network_task, 20, 30},
                         /*{-1, store_image_task, 20, 500},*/
                         {-1, keyboard_task, 30, 15}};
    const int n_task = sizeof(task_table) / sizeof(Task);

    pthread_mutex_init(&mutex_data, NULL);

    mkdir(PATH_I_NN, 0755);
    init_interface();

    /* Global bitmap for storing the colored image generated by the values
     * ​​sampled by the sensor */
    image = create_bitmap(EL_W, ACT_IMG_H);

    for (index = 0; index < n_task; index++)
        task_create(&task_table[index]);

    do {
    } while (pthread_join(task_table[n_task - 1].id, NULL));

    for (index = 0; index < n_task - 1; index++)
        pthread_cancel(task_table[index].id);

    allegro_exit();
    return 0;
}